FROM ubuntu:16.04
MAINTAINER sczyh30 <sczyh16@gmail.com>

COPY main /usr/local/bin/waffle-brain-server
RUN chmod +x /usr/local/bin/waffle-brain-server
ENTRYPOINT ["/usr/local/bin/waffle-brain-server"]